# ベースのコンテナイメージ
FROM eclipse-temurin:21-jdk

# 必要なツールをインストール
RUN apt update && apt install -y \
    maven \
    && apt clean

# 作業ディレクトリを設定
WORKDIR /app

# プロジェクトのソースコードをコピー
COPY . .

# Mavenでプロジェクトをビルド
RUN mvn clean package

# JARファイルを実行
ENTRYPOINT ["java", "-jar", "target/apiGateway-1.0-SNAPSHOT.jar"]
