# ベースのコンテナイメージ
FROM eclipse-temurin:21-jdk-jammy

# 必要なツールをインストール
RUN apt-get  update && apt-get  install -y  --no-install-recommends \
    maven \
    && apt-get clean

# 作業ディレクトリを設定
WORKDIR /app

# プロジェクトのソースコードをコピー
COPY . .

# Mavenでプロジェクトをビルド
RUN mvn clean package

# JARファイルを実行
ENTRYPOINT ["java", "-jar", "target/apiGateway-1.0-SNAPSHOT.jar"]
